# Generated by Django 6.0.3 on 2026-03-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default=23232, max_length=255),
            preserve_default=False,
        ),
    ]
